#Diamond Rush Save
#Tue Apr 28 12:59:12 PST 2026
autoLevel=0
gem_DIAMOND=false
gem_EMERALD=false
gem_GOLD=false
gem_IRON=false
gem_RUBY=false
gem_SAPPHIRE=false
mineLevel=0
pickLevel=0
score=0.0
skin_JACKHAMMER=false
skin_PICKAXE=false
skin_SHOVEL=false
totalClicks=0
